### ISSUE TITLE
% character is not escaped in book lookup

### ISSUE THREAD

**Issue by STommydx** [Derppening/comp4111-project#19]
**Describe the bug**
`%` character is not escaped in LIKE statements in book searching criteria.

**To Reproduce**
1. Login as usual
2. Add the following book
```json
{
            "Title": "Book 25!",
            "Author": "Author",
            "Publisher": "Publisher",
            "Year": "2028"
}
```
3. Search book containing title specified below
`GET localhost:8080/BookManagementService/books?token={{token}}&title=%25`

**Expected behavior**
`204 No Content`

**What actually happens**
`200 OK` with the book returned
```json
{
    "FoundBooks": 1,
    "Results": [
        {
            "Title": "Book 25!",
            "Author": "Author",
            "Publisher": "Publisher",
            "Year": "2028"
        }
    ]
}
```
**Notes**
The result should be `204 No Content` no matter you choose to implement url encoding or not :wink:

**Comment by davidtang1006** [comment]
I would try to argue that the parameter `title` accepts LIKE wildcards.

1. Run [this custom JMeter test plan](https://github.com/Derppening/comp4111-project/files/4705481/custom-test-plan_.-character.zip).
2. Type `http://localhost:8080/BookManagementService/books?title=B%k&token=${token}` in a browser. The result should be `{"FoundBooks":2,"Results":[{"Title":"Book 25","Author":"Author","Publisher":"Publisher","Year":2028},{"Title":"Book %26","Author":"Author","Publisher":"Publisher","Year":2028}]}`. This shows that `title` indeed accepts the wildcard `%`.
3. If one wants to search for an actual `%`, use `\%`. Type `http://localhost:8080/BookManagementService/books?title=\%&token=${token}` in the browser. The result should be `{"FoundBooks":1,"Results":[{"Title":"Book %26","Author":"Author","Publisher":"Publisher","Year":2028}]}`.
4. Log out by `http://localhost:8080/BookManagementService/logout?token=${token}`.

Some of the paths shown above somehow break JMeter, so use a browser instead.

**Comment by davidtang1006** [comment]
Need more information from @comp4111ta :man_shrugging:.

**Comment by comp4111ta** [comment]
Undefined Behavior.
