### ISSUE TITLE
[Security] Transactions are not isolated between users

### ISSUE THREAD

**Issue by STommydx** [Derppening/comp4111-project#20]
**Describe the bug**
Transactions are not isolated between users. That is, a user can execute other users' transactions by transaction id.

**To Reproduce**
1. Login as `user00001`. 
2. Create a book. Should return book ID `1` for empty db.
3. Obtain a transaction id. Let the result be `{{tid}}`.
4. Login as `user00002`. 
5. Add an action to the transaction with the below payload.
```json
{
	"Transaction" : {{tid}},
	"Book" : 1,
	"Action": "loan"
}
```

**Expected behavior**
`400 Bad Request`

**What actually happens**
`200 OK`

**Comment by Derppening** [comment]
Hmm... I could see how this may impose a security risk. However, given the uniqueness of the transaction ID, I think this case is highly unlikely.

Still, if @comp4111ta decides this as a security bug, I will accept it.

**Comment by davidtang1006** [comment]
The transaction ID should be an absolute value `Long` generated by `SecureRandom`. So basically, the transaction ID is treated like an access token. The chance of guessing a particular transaction ID is about ![formula](https://render.githubusercontent.com/render/math?math=\frac{1}{2^{63}}). Around ![formula](<https://render.githubusercontent.com/render/math?math=2^{\frac{63}{2}} \approx 3.04\ \textrm{billion}>) transactions are expected to find a collision of transaction ID.

At this point, I think it is safe to claim that one cannot guess another user's transaction ID unless it is leaked. If it is leaked, this is similar to telling a password/access token to an attacker. This is not supposed to happen or be deemed as a security issue.

**Comment by comp4111ta** [comment]
Undefined Behavior.
